import localFont from "next/font/local";
import "./globals.css";
import AdminSidebar from "./component/admin/Admin-Sidebar";
import AdminHeader from "./component/admin/Admin-header";
import { AuthProvider } from "@/app/context/context"
import { Toaster, toast } from 'sonner'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "BrandKicks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="min-h-screen bg-gray-100">
            <AdminHeader />
              <div className="flex">
                <AdminSidebar />
                <main className="flex-1 p-6 overflow-auto">{children}</main>
                <Toaster richColors/>
            </div>    
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
